config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'pages/splash'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'pages#splash'
  resources :users
  resources :categories do
    resources :budgets
  end
end

app/models/budget.rb
class Budget < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: 'author_id'
  has_many :budget_categories, class_name: 'BudgetCategory', foreign_key: 'budget_id', dependent: :destroy
  has_many :categories, through: :budget_categories

  validates :name, presence: true, length: { maximum: 255 }
  validates :amount, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController
  before_action :authenticate_user!

  def new
    @category = Category.find(params[:cat])
    @budget = Budget.new
  end

  def create
    @original = Category.find(params[:cat])
    @cate = Category.where(name: params[:budget][:category].downcase, author_id: current_user.id).first
    @transaction = Budget.new(transaction)
    @transaction.author_id = current_user.id
    if @cate.nil?
      flash[:alert] = 'The category does not exist, create the category'
      # redirect_to category_path(@original.id)
      redirect_to categories_path
    else
      @transaction.save
      p @transaction
      p @cate
      @complete = BudgetCategory.new(budget_id: @transaction.id, category_id: @cate.id)
      p @complete.errors.full_messages
      @complete.save
      redirect_to category_path(@cate.id)
    end
  end

  private

  def transaction
    params.require(:budget).permit(:name, :amount)
  end
end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/views/budgets/new.html.erb
<%= render partial: "shared/navbar", locals: {logo: "New Budget", model: category_path(@category.id)}%>

<div class = "form up">
<%=form_with model:@budget, url: category_budgets_path(@category.id, cat: @category.id) do |f|%>
  <h2 class="exc"> create Transaction</h2>
  <div class="input">
    <%=f.label :name%>
    <%=f.text_field :name, placeholder: "transaction name", required:true %>
  </div>
  <div class="input">
    <%=f.label :amount%>
    <%=f.text_field :amount, placeholder: "amount", required:true %>
  </div>
   <div class="input">
    <%=f.label :category%>
    <%=f.text_field :category, placeholder: "category", required:true %>
  </div>
  <div class="actions ex">
    <%=f.submit "create transaction", disable_with: 'create transactioning...', class: "add-cat-btn"%>
  </div>
<%end%>
</div>