config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'pages/splash'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'pages#splash'
  resources :users
  resources :categories do
    resources :budgets
  end
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: 'author_id'
  has_many :budget_categories, class_name: 'BudgetCategory', foreign_key: 'category_id', dependent: :destroy
  has_many :budgets, through: :budget_categories
  has_one_attached :icon

  validates :name, presence: true, length: { maximum: 255 }
  validates :icon, presence: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!

  def index
    @categories = Category.where(author_id: current_user.id)
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    @category.author_id = current_user.id

    if @category.save
      flash[:success] = 'A New Category successfully created'
      redirect_to categories_path
    else
      flash[:error] = 'Something went wrong'
      puts @category.errors.full_messages
      render 'new'
    end
  end

  private

  def category_params
    name_case = params.require(:category).permit(:icon, :name)
    name_case[:name] = name_case[:name].downcase
    name_case
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/index.html.erb
<%= render partial: "shared/navbar", locals: {logo: "Category", model: categories_path} %>

  <div class="categories-table">
    <% @categories.each do |category| %>
      <div class="category">
        <div class="img-name">        
          <div class="category-img">        
            <%= image_tag category.icon if category.icon.attached? %>
          </div>
          <%= link_to category.name, category_path(category.id), class: "category-name" %>       
        </div>
        <p class="category-name">$<%= category.budgets.sum(:amount) %> </p>       
      </div>
    <% end %>
    <div class="category-btn-cont">      
    <%= link_to "ADD CATEGORY", new_category_path, class: "add-cat-btn" %>
    </div>
</div>  

app/views/categories/new.html.erb
<%= render partial: "shared/navbar", locals: {logo: "New Category", model: categories_path}%>

<div class='form up'>
<h3 class="cat-header"> Add New Category </h3>
<%= form_with model:@category, url: categories_path do |form| %>
<div class='form-inputs'>   
    <div class="row">
      <div class="input-field col s12">
        <input id="category_name" type="text" value="" class="validate" name="category[name]" placeholder="Name" required autofocus>
        <label for="category_name"></label>
      </div>
</div>
    <div class="form_field">
      <%= form.file_field :icon, id: "category_photo_input", class: "waves-effect waves-light btn" %>
    </div>
    <div id="category_photo_preview"></div> 
    <div>
      <%= form.submit placeholder: "create category", class: "waves-effect waves-light btn, add-cat-btn"%>
    </div>
  </div>
<%end%>
</div>

app/views/categories/show.html.erb
<%= render partial: "shared/navbar", locals: {logo: "$#{@category.budgets.sum(:amount)}", model: categories_path }%>

  <div class="categories-table">
    <% @category.budgets.each do |budget| %>
      <div class="category">     
        <p class="category-name"><%= budget.name %> </p>       
        <p class="category-name">$<%= budget.amount %> </p>       
      </div>
    <% end %>
    <div class="category-btn-cont">      
        <%= link_to "Add New Transaction", new_category_budget_path(@category.id, cat: @category.id), class: "add-cat-btn" %>
    </div>
</div>  